name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no . /stone-collection-project/stone-collection-project-backend

      - name: Install dependencies and restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ip-172-31-35-85 << 'EOF'
            cd /stone-collection-project/stone-collection-project-backend
            npm install
            pm2 restart test.js
          EOF