name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure local directory exists
        run: mkdir -p stone-collection-project/stone-collection-project-backend

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Pull latest changes from master
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-208-198-41.compute-1.amazonaws.com 'cd /home/ec2-user/stone-collection-project/stone-collection-project-backend && git pull origin master'

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no stone-collection-project/stone-collection-project-backend ec2-user@ec2-18-208-198-41.compute-1.amazonaws.com:/home/ec2-user/stone-collection-project/

      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-208-198-41.compute-1.amazonaws.com 'cd /home/ec2-user/stone-collection-project/stone-collection-project-backend && npm install'

      - name: Restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-208-198-41.compute-1.amazonaws.com 'cd /home/ec2-user/stone-collection-project/stone-collection-project-backend && pm2 restart test.js'
